alfresco-repository:
  resources:
    requests:
      cpu: "0.01"
      memory: "1024Mi"
    limits:
      memory: "1560Mi"    
    replicaCount: 1      
alfresco-transform-service:
  pdfrenderer:
    resources:
      requests:
        cpu: "0.01"
        memory: "256Mi"
      limits:
        memory: "512Mi"      
    replicaCount: 1      
  imagemagick:
    resources:
      requests:
        cpu: "0.01"
        memory: "256Mi"
      limits:
        memory: "1Gi"      
    replicaCount: 1      
  libreoffice:
    resources:
      requests:
        cpu: "0.01"
        memory: "512Mi"
      limits:
        memory: "1024Mi"
    replicaCount: 1      
  tika:
    resources:
      requests:
        cpu: "0.01"
        memory: "256Mi"
      limits:
        memory: "512Mi"
    replicaCount: 1      
  transformmisc:
    resources:
      requests:
        cpu: "0.01"
        memory: "256Mi"
      limits:
        memory: "512Mi"
    replicaCount: 1      
share:
  resources:
    requests:
      cpu: "0.01"
      memory: "256Mi"
    limits:
      memory: "512Mi" 
  replicaCount: 1   
alfresco-search:
  resources:
    requests:
      cpu: 0.1
      memory: "1000Mi"
    limits:
      memory: "1500Mi"    
  replicaCount: 1   
postgresql:
  primary:
    resources:
      requests:
        cpu: "0.1"
        memory: "500Mi"
      limits:
        memory: "500Mi"